// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/folder.proto

package shared

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	FileSize      int64                  `protobuf:"varint,4,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_proto_folder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_folder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_proto_folder_proto_rawDescGZIP(), []int{0}
}

func (x *FileChunk) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *FileChunk) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *FileChunk) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

type UploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	FilesCount    int32                  `protobuf:"varint,3,opt,name=files_count,json=filesCount,proto3" json:"files_count,omitempty"`
	TotalBytes    int64                  `protobuf:"varint,4,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_proto_folder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_folder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_proto_folder_proto_rawDescGZIP(), []int{1}
}

func (x *UploadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UploadResponse) GetFilesCount() int32 {
	if x != nil {
		return x.FilesCount
	}
	return 0
}

func (x *UploadResponse) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

type DownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FolderPath    string                 `protobuf:"bytes,1,opt,name=folder_path,json=folderPath,proto3" json:"folder_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_proto_folder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_folder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_proto_folder_proto_rawDescGZIP(), []int{2}
}

func (x *DownloadRequest) GetFolderPath() string {
	if x != nil {
		return x.FolderPath
	}
	return ""
}

var File_proto_folder_proto protoreflect.FileDescriptor

const file_proto_folder_proto_rawDesc = "" +
	"\n" +
	"\x12proto/folder.proto\x12\x06folder\"k\n" +
	"\tFileChunk\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x1b\n" +
	"\tfile_size\x18\x04 \x01(\x03R\bfileSizeJ\x04\b\x03\x10\x04J\x04\b\x05\x10\x06\"\x86\x01\n" +
	"\x0eUploadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vfiles_count\x18\x03 \x01(\x05R\n" +
	"filesCount\x12\x1f\n" +
	"\vtotal_bytes\x18\x04 \x01(\x03R\n" +
	"totalBytes\"2\n" +
	"\x0fDownloadRequest\x12\x1f\n" +
	"\vfolder_path\x18\x01 \x01(\tR\n" +
	"folderPath2\x8d\x01\n" +
	"\x0eFolderTransfer\x12;\n" +
	"\fUploadFolder\x12\x11.folder.FileChunk\x1a\x16.folder.UploadResponse(\x01\x12>\n" +
	"\x0eDownloadFolder\x12\x17.folder.DownloadRequest\x1a\x11.folder.FileChunk0\x01B\x18Z\x16folder-transfer/sharedb\x06proto3"

var (
	file_proto_folder_proto_rawDescOnce sync.Once
	file_proto_folder_proto_rawDescData []byte
)

func file_proto_folder_proto_rawDescGZIP() []byte {
	file_proto_folder_proto_rawDescOnce.Do(func() {
		file_proto_folder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_folder_proto_rawDesc), len(file_proto_folder_proto_rawDesc)))
	})
	return file_proto_folder_proto_rawDescData
}

var file_proto_folder_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_folder_proto_goTypes = []any{
	(*FileChunk)(nil),       // 0: folder.FileChunk
	(*UploadResponse)(nil),  // 1: folder.UploadResponse
	(*DownloadRequest)(nil), // 2: folder.DownloadRequest
}
var file_proto_folder_proto_depIdxs = []int32{
	0, // 0: folder.FolderTransfer.UploadFolder:input_type -> folder.FileChunk
	2, // 1: folder.FolderTransfer.DownloadFolder:input_type -> folder.DownloadRequest
	1, // 2: folder.FolderTransfer.UploadFolder:output_type -> folder.UploadResponse
	0, // 3: folder.FolderTransfer.DownloadFolder:output_type -> folder.FileChunk
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_folder_proto_init() }
func file_proto_folder_proto_init() {
	if File_proto_folder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_folder_proto_rawDesc), len(file_proto_folder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_folder_proto_goTypes,
		DependencyIndexes: file_proto_folder_proto_depIdxs,
		MessageInfos:      file_proto_folder_proto_msgTypes,
	}.Build()
	File_proto_folder_proto = out.File
	file_proto_folder_proto_goTypes = nil
	file_proto_folder_proto_depIdxs = nil
}
