// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/folder.proto

package shared

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FolderTransfer_UploadFolder_FullMethodName   = "/folder.FolderTransfer/UploadFolder"
	FolderTransfer_DownloadFolder_FullMethodName = "/folder.FolderTransfer/DownloadFolder"
)

// FolderTransferClient is the client API for FolderTransfer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FolderTransferClient interface {
	UploadFolder(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileChunk, UploadResponse], error)
	DownloadFolder(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChunk], error)
}

type folderTransferClient struct {
	cc grpc.ClientConnInterface
}

func NewFolderTransferClient(cc grpc.ClientConnInterface) FolderTransferClient {
	return &folderTransferClient{cc}
}

func (c *folderTransferClient) UploadFolder(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileChunk, UploadResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FolderTransfer_ServiceDesc.Streams[0], FolderTransfer_UploadFolder_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileChunk, UploadResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FolderTransfer_UploadFolderClient = grpc.ClientStreamingClient[FileChunk, UploadResponse]

func (c *folderTransferClient) DownloadFolder(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FolderTransfer_ServiceDesc.Streams[1], FolderTransfer_DownloadFolder_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadRequest, FileChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FolderTransfer_DownloadFolderClient = grpc.ServerStreamingClient[FileChunk]

// FolderTransferServer is the server API for FolderTransfer service.
// All implementations must embed UnimplementedFolderTransferServer
// for forward compatibility.
type FolderTransferServer interface {
	UploadFolder(grpc.ClientStreamingServer[FileChunk, UploadResponse]) error
	DownloadFolder(*DownloadRequest, grpc.ServerStreamingServer[FileChunk]) error
	mustEmbedUnimplementedFolderTransferServer()
}

// UnimplementedFolderTransferServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFolderTransferServer struct{}

func (UnimplementedFolderTransferServer) UploadFolder(grpc.ClientStreamingServer[FileChunk, UploadResponse]) error {
	return status.Error(codes.Unimplemented, "method UploadFolder not implemented")
}
func (UnimplementedFolderTransferServer) DownloadFolder(*DownloadRequest, grpc.ServerStreamingServer[FileChunk]) error {
	return status.Error(codes.Unimplemented, "method DownloadFolder not implemented")
}
func (UnimplementedFolderTransferServer) mustEmbedUnimplementedFolderTransferServer() {}
func (UnimplementedFolderTransferServer) testEmbeddedByValue()                        {}

// UnsafeFolderTransferServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FolderTransferServer will
// result in compilation errors.
type UnsafeFolderTransferServer interface {
	mustEmbedUnimplementedFolderTransferServer()
}

func RegisterFolderTransferServer(s grpc.ServiceRegistrar, srv FolderTransferServer) {
	// If the following call panics, it indicates UnimplementedFolderTransferServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FolderTransfer_ServiceDesc, srv)
}

func _FolderTransfer_UploadFolder_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FolderTransferServer).UploadFolder(&grpc.GenericServerStream[FileChunk, UploadResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FolderTransfer_UploadFolderServer = grpc.ClientStreamingServer[FileChunk, UploadResponse]

func _FolderTransfer_DownloadFolder_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FolderTransferServer).DownloadFolder(m, &grpc.GenericServerStream[DownloadRequest, FileChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FolderTransfer_DownloadFolderServer = grpc.ServerStreamingServer[FileChunk]

// FolderTransfer_ServiceDesc is the grpc.ServiceDesc for FolderTransfer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FolderTransfer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "folder.FolderTransfer",
	HandlerType: (*FolderTransferServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadFolder",
			Handler:       _FolderTransfer_UploadFolder_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "DownloadFolder",
			Handler:       _FolderTransfer_DownloadFolder_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/folder.proto",
}
